### ISSUE TITLE
inconsistent use of count and getCount

### ISSUE THREAD

**Issue by MoreSaltMoreLemon** [learn-co-curriculum/fewpjs-oo-class-extension-and-inheritance-extends#10]
both of the subclasses are required to have a getter method `count` in in their tests while the superclass has a method called `getCount`. If you're teaching inheritance, seems like it would be good to use inheritance.

**Comment by drakeltheryuujin** [comment]
Hi @MoreSaltMoreLemon,
This issue appears to be opened on the wrong lesson. Thanks for your feedback! I'm going to close this for now and address this on the [lab](https://github.com/learn-co-curriculum/fewpjs-class-extensions-extends-lab/) it pertains to.
